title: Shuffering & Shmiling The blog
author: Humanity Desmond
email: shufferingandshmiling@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Information & Miscellany.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
